services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - laravel

    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - laravel

    redis:
        image: redis:latest
        networks:
            - laravel

    db:
        container_name: db
        image: postgres:16
        restart: always
        shm_size: 1g
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: password
            POSTGRES_USER: postgres
            POSTGRES_DB: crud
        networks:
            - laravel

networks:
    laravel:
        driver: bridge
